name: Refresh test & build cache & build latest wth debug symbols
on:
  workflow_dispatch:
  
jobs:
  include-build-envoy-images-release-base:
    uses: ./.github/workflows/build-envoy-images-release-base.yaml
    with:
      release_debug: 'true'
    secrets: inherit
